version: '3.8'

services: 
  web:
    build: 
      context: DistributedTransactionsApi
      dockerfile: Dockerfile
    image: distributed-transactions-api:v0.0.1
    pull_policy: build
    ports: 
      - "127.0.0.1:${PORT:-8000}:8080"
  
      